# Replace the text below to customize your site
site_name: Your name
site_description: Your name Fabricademy site
site_author: Your name
copyright: Copyright 2021 Your name - Creactive Commons Attribution Non-commercial

site_url: http://academany.fabcloud.io/fabricademy/2021/student-template/
repo_url: https://gitlab.fabcloud.org/academany/fabricademy/2021/student-template
repo_name: Edit on Fabcloud

extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/fabricademy
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/fabricademy
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/fabricademy

theme:
  name: material
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: yellow
    accent: deep purple
  font:
    # See available fonts at https://fonts.google.com/
    text: Montserrat
    code: Roboto Mono
  icon:
    logo: material/car
    repo: material/gitlab
  features:
    - tabs

plugins:
  - search
  - git-revision-date-localized

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
