site_name: Jorge correa
site_description: Fabricademy 2020
site_author: Jorge correa
copyright: Copyright 2021 Jorge Correa - Creactive Commons Attribution Non-commercial

site_url: https://class.textile-academy.org/2021/jorge-correa/
repo_url: https://gitlab.fabcloud.org/academany/fabricademy/2021/students/jorge.correa
repo_name: Edit on Fabcloud

extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/mr.j_snap/

theme:
  name: material
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: green
    accent: green
  font:
    # See available fonts at https://fonts.google.com/
    text: Ubuntu
    code: Roboto Mono
  icon:
    logo: material/library
    repo: material/gitlab
  features:
    - tabs

plugins:
  - search
  - git-revision-date-localized

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
